// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZGLckIGCKsWLJflEfLvgk3TXFlDCFlE4',
    appId: '1:624661796727:web:a6346c4ccaac3ff1cff372',
    messagingSenderId: '624661796727',
    projectId: 'authreserva-a42ba',
    authDomain: 'authreserva-a42ba.firebaseapp.com',
    storageBucket: 'authreserva-a42ba.appspot.com',
    measurementId: 'G-JW5V5LMVPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwqEA5UU0KCsXzthAY8hu3_HyJgO5mdOQ',
    appId: '1:624661796727:android:4e7e119b09a86d1ecff372',
    messagingSenderId: '624661796727',
    projectId: 'authreserva-a42ba',
    storageBucket: 'authreserva-a42ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8QqLIqtYSrafcBU58COilXmzDMx9I6yU',
    appId: '1:624661796727:ios:859f083e1fd40929cff372',
    messagingSenderId: '624661796727',
    projectId: 'authreserva-a42ba',
    storageBucket: 'authreserva-a42ba.appspot.com',
    androidClientId: '624661796727-t8c81l1dto39hl4fb92tq8dofrc7o13k.apps.googleusercontent.com',
    iosClientId: '624661796727-g2h1jr0ns1mdq5d6nmmtik64mj3pcu46.apps.googleusercontent.com',
    iosBundleId: 'com.example.reservaMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8QqLIqtYSrafcBU58COilXmzDMx9I6yU',
    appId: '1:624661796727:ios:859f083e1fd40929cff372',
    messagingSenderId: '624661796727',
    projectId: 'authreserva-a42ba',
    storageBucket: 'authreserva-a42ba.appspot.com',
    androidClientId: '624661796727-t8c81l1dto39hl4fb92tq8dofrc7o13k.apps.googleusercontent.com',
    iosClientId: '624661796727-g2h1jr0ns1mdq5d6nmmtik64mj3pcu46.apps.googleusercontent.com',
    iosBundleId: 'com.example.reservaMovil',
  );
}
